//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "flickr_photoset_tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub flickr_id: u64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::flickr_photoset::Entity",
        from = "Column::FlickrId",
        to = "super::flickr_photoset::Column::FlickrId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FlickrPhotoset,
    #[sea_orm(
        belongs_to = "super::tag::Entity",
        from = "Column::TagId",
        to = "super::tag::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tag,
}

impl Related<super::flickr_photoset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlickrPhotoset.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
