//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "flickr_photoset")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub flickr_id: u64,
    pub user_id: u64,
    pub title: String,
    pub description: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::flickr_photoset_tag::Entity")]
    FlickrPhotosetTag,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::flickr_photoset_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlickrPhotosetTag.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::flickr_photoset_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::flickr_photoset_tag::Relation::FlickrPhotoset
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
