//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod directory;
pub mod flickr_photo;
pub mod flickr_photo_size;
pub mod flickr_photoset;
pub mod flickr_photoset_tag;
pub mod photo;
pub mod photo_file;
pub mod photo_reaction;
pub mod photo_tag;
pub mod sea_orm_active_enums;
pub mod tag;
pub mod user;
