//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "photo_file")]
pub struct Model {
    pub photo_id: u64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub directory_id: u64,
    pub name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub integrity: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directory::Entity",
        from = "Column::DirectoryId",
        to = "super::directory::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Directory,
    #[sea_orm(
        belongs_to = "super::photo::Entity",
        from = "Column::PhotoId",
        to = "super::photo::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Photo,
}

impl Related<super::directory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Directory.def()
    }
}

impl Related<super::photo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Photo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::directory::Entity")]
    Directory,
    #[sea_orm(entity = "super::photo::Entity")]
    Photo,
}
