//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::directory::Entity as Directory;
pub use super::flickr_photo::Entity as FlickrPhoto;
pub use super::flickr_photo_size::Entity as FlickrPhotoSize;
pub use super::flickr_photoset::Entity as FlickrPhotoset;
pub use super::flickr_photoset_tag::Entity as FlickrPhotosetTag;
pub use super::photo::Entity as Photo;
pub use super::photo_file::Entity as PhotoFile;
pub use super::photo_reaction::Entity as PhotoReaction;
pub use super::photo_tag::Entity as PhotoTag;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
